defaults:
  - _self_
  - policy: ppo

env:
  action_scale: 0.5
  hip_scale: 0.6
  control_mode: "VIC_2"
  physics_steps_per_control_step: 4

  num_history_actor: 1 # number of previous observations to stack
  num_history_critic: 1 # number of previous observations to stack
  kick_vel: 0.5
  push_interval: 100
  is_training: False
  episode_length: 500

  default_pos: [0, 0, 0.32, 1, 0, 0, 0, -0.1, 0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 1.0, -1.5, 0.1, 1.0, -1.5] 
  #default_pos: [0, 0, 0.35, 1, 0, 0, 0, -0.1, 0.9, -1.8, 0.1, 0.9, -1.8, -0.1, 0.9, -1.8, 0.1, 0.9, -1.8]

  single_obs_size: 48
  single_obs_size_priv: 59

  domain_rand:
    randomisation: True
    gravity_offset: [-1., 1.]
    friction_range: [0.3, 1.25]
    payload_range: [-1., 3.]
    hip_mass_range: [-0.3, 0.3]
    kp_range: [0.8, 1.3]
    kd_range: [0.5, 1.5]
    motor_strength_range: [0.9, 1.1]

    local_v_noise: 0.1
    local_w_noise: 0.2
    joint_noise: 0.01
    joint_vel_noise: 1.5
    gravity_noise: 0.05

  normalization:
    local_v_scale: 2.0
    local_w_scale: 0.25
    joint_vel_scale: 0.1
    command_scale: 2.0

  manual_control:
    enable: True
    cmd_x: 0.8
    cmd_y: 0.0
    cmd_ang: 0.0

  reset_pos_x: [-5.0, 5.0]
  reset_pos_y: [-5.0, 5.0]

  control:
    stiff_range: [0.5, 2.0]
    p_gain: 50.0
    d_gain: 1.0


ckpt_path: 'outputs/2024-11-22/17-35-39/checkpoints/model_900.pt' # 'outputs/2024-11-08/15-11-03/checkpoints/last.pt' #'best_models/test_vic1.pt' #'best_models/test_vic_2_oldpose.pt' #'best_models/test_pos_priv.pt' # # #'best_models/test_p_oldpose.pt' # #  # #'outputs/2024-09-16/18-45-14/checkpoints/model_2000.pt' # ## #'best_models/test_vic1.pt' #
timesteps_per_rollout: 100
num_iterations: 10
num_envs: 200


viz: True
device: 'cuda:0'
curriculum: False
scene_xml: 'unitree_go2/flat.xml'